= Kubernetes Refcardz
:toc:
:toc-placement!:

toc::[]

Kubernetes is an open source orchestration system for managing containerized applications across multiple hosts, providing basic mechanisms for deployment, maintenance, and scaling of applications.

Kubernetes, or "`k8s`" in short, allows the user to provide declarative primitives for the desired state, for example “need 3 Couchbase servers running”. Kubernetes self-healing mechanisms, such as auto-restarting, re-scheduling, and replicating containers then ensure that this state is met.

Kubernetes supports Docker and Rocket containers, and other container image formats and container runtimes will be supported in the future.

== Key Concepts

*Cluster*: A Kubernetes cluster is a set of physical or virtual machines and other infrastructure resources that are used running your applications. The machines that manage the cluster are called _Master_ and the machines that run the containers are called _Worker_.

*Master*: A master is the central control point that provides a unified view of the cluster. Multiple masters can be setup to create a high-availability cluster.

*Node* (nee "`minion`"): A node is a physical or virtual machine running Kubernetes, onto which pods can be scheduled.

*Pod*: A Pod is the smallest deployable units that can be created, scheduled, and managed. Its a logical collection of containers that belong to an application.

Each resource in Kubernetes is defined using a configuration file. For example, a Couchbase pod might be defined as:

[source, text]
----
apiVersion: v1
kind: Pod
metadata:
  name: couchbase
spec:
  containers:
  - name: couchbase
    image: couchbase
    ports:
    - containerPort: 8091
----

Replication Controller

Service

Label

Kubectl CLI

== Getting Started with Kubernetes

Vagrant
Start the cluster
Kubectl script

Several options are available but the most common ones are GCE, AWS, Azure

== Run your first Docker container

== Kubernetes Configuration File

== Scale Applications

== Connecting Containers using Service

== Volumes

== Health Check

== Debugging

== About the Author

Arun Gupta is the vice president of developer advocacy at Couchbase. He has been building developer communities for 10+ years at Sun, Oracle, and Red Hat. He has deep expertise in leading cross-functional teams to develop and execute strategy, planning and execution of content, marketing campaigns, and programs. Prior to that he led engineering teams at Sun and is a founding member of the Java EE team.

Gupta has authored more than 2,000 blog posts on technology. He has extensive speaking experience in more than 40 countries on myriad topics and is a JavaOne Rock Star. Gupta also founded the Devoxx4Kids chapter in the US and continues to promote technology education among children. An author of a best-selling book, an avid runner, a globe trotter, a Java Champion, and a JUG leader, he is easily accessible at @arungupta.
